"""Initial migration 2

Revision ID: c823e32b9443
Revises: 87f8b607650e
Create Date: 2026-07-14 22:10:38.515709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c823e32b9443'
down_revision: Union[str, Sequence[str], None] = '87f8b607650e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('status_label', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('issues', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('status_label', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=2048), nullable=True),
    sa.Column('extracted', sa.JSON(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('package_version_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=1024), nullable=False),
    sa.Column('detected_type', sa.String(length=50), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_version_id'], ['package_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('package_version_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=2048), nullable=False),
    sa.ForeignKeyConstraint(['package_version_id'], ['package_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues')
    op.drop_table('documents')
    op.drop_table('package_versions')
    op.drop_table('packages')
    op.drop_table('checks')
    # ### end Alembic commands ###
